### ISSUE TITLE
Children processes not terminating

### ISSUE THREAD

**Issue by wedobetter** [cirospaciari/socketify.py#103]
**Children processes not terminating**
Children processes keep running in the background after Ctrl+C app

**To Reproduce**
1.  Run: ```pypy -m socketify main:run -h localhost -w 8 -p 8000```
2. Exit: ```Ctrl+C```
3. ```ps aux | grep pypy```

**Expected behavior**
The parent process should kill its children on exiting

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS: Mac M1 arm64

<img width="1058" alt="Screenshot 2023-02-22 at 23 00 16" src="https://user-images.githubusercontent.com/31860030/220782709-6178307d-d658-4956-9bc1-9cbcd1423f38.png">

After killing the parent process 67804 all other processes keep running in the background.

 - Version [0.0.16]

**Comment by cirospaciari** [comment]
I can confirm this issue, will be fixed in next release

**Comment by cirospaciari** [comment]
Fixed on 23f6e26d264c893ac9c0696064272e3664a36290
