### ISSUE TITLE
Investigate strawberry performance using async + PyPy

### ISSUE THREAD

**Issue by cirospaciari** [cirospaciari/socketify.py#104]
@wedobetter related some weird cases, we need to investigate, not only async but sync, and also CPython and other popular libraries, for this Issue, investigating strawberry async + PyPy is the priority.

In recent raw async coroutines performance PyPy is faster than vibora and in CPython is faster than Japronto, with really good results. The last version removed a lot of overhead from async, probably this is some weird use of async by the library itself.

Recent TFB preliminary tests show that version v0.0.16 (the same as the strawberry problem) is really fast in ASGI and async in both CPython and PyPy so raw async probably is not the problem:

https://www.techempower.com/benchmarks/#section=test&runid=328ef78f-93c0-4e5d-a5c1-69b5ceb95064&test=plaintext&l=hra0hr-35r

Screenshot provided by @wedobetter

<img width="907" alt="Screenshot 2023-02-24 at 14 45 33" src="https://user-images.githubusercontent.com/31860030/221207666-9b37df8f-8d45-4253-92b2-cd678219daaf.png">

PyPy when accessing C Extensions can be slower than CPython (Cython is a popular one, this will change with HPy), maybe this is the case.

**Comment by wedobetter** [comment]
Thank you @cirospaciari, I should have raised a separate issue, my bad!

Here's how to reproduce it:
```python
from socketify import App
import strawberry
from strawberry.types import Info
from strawberry.utils.graphiql import get_graphiql_html

from graphiql import graphiql_from


@strawberry.type
class User:
    name: str


@strawberry.type
class Query:
    @strawberry.field
    async def user(self, info: Info) -> User | None:
        return User(name="Hello")


def run(app: App):
    app.get("/", lambda res, req: res.end(get_graphiql_html()))
    app.post("/", graphiql_from(Query))
    # you can also pass a Mutation as second parameter
    # app.post("/", graphiql_from(Query, Mutation))
    app.listen(
        8000,
        lambda config: print(f"Listening on port http://localhost:{config.port} now\n"),
    )
    app.run()


run(App())
```

If you remove that `async` from the Query, you get awesome performance again ;)

**Comment by cirospaciari** [comment]
> Thank you @cirospaciari, I should have raised a separate issue, my bad!
> 
> Here's how to reproduce it:
> 
> ```python
> from socketify import App
> import strawberry
> from strawberry.types import Info
> from strawberry.utils.graphiql import get_graphiql_html
> 
> from graphiql import graphiql_from
> 
> 
> @strawberry.type
> class User:
>     name: str
> 
> 
> @strawberry.type
> class Query:
>     @strawberry.field
>     async def user(self, info: Info) -> User | None:
>         return User(name="Hello")
> 
> 
> def run(app: App):
>     app.get("/", lambda res, req: res.end(get_graphiql_html()))
>     app.post("/", graphiql_from(Query))
>     # you can also pass a Mutation as second parameter
>     # app.post("/", graphiql_from(Query, Mutation))
>     app.listen(
>         8000,
>         lambda config: print(f"Listening on port http://localhost:{config.port} now\n"),
>     )
>     app.run()
> 
> 
> run(App())
> ```
> 
> If you remove that `async` from the Query, you get awesome performance again ;)

No problems, thanks for the feedback this is really helpful to me and to the project.
Maybe this is something with task factory, can you try to run it with: ` --task-factory-maxitems 0` at the end of the CLI command?

**Comment by wedobetter** [comment]
Unfortunately, that doesn't make a difference

**Comment by cirospaciari** [comment]
Both CPython and PyPy have weird fluctuations here:

CPython:
![image](https://user-images.githubusercontent.com/6379399/221242978-07c4cb1c-79cf-4979-9345-da2cbb0cec5f.png)

PyPy:
![image](https://user-images.githubusercontent.com/6379399/221243151-bf807ad1-5305-4fef-ba63-5b739111404a.png)

Without async both are really fast!

The process is always async for socketify the code:

```python
def graphiql_from(Query, Mutation=None):
    if Mutation:
        schema = strawberry.Schema(query=Query, mutation=Mutation)
    else:
        schema = strawberry.Schema(Query)

    async def post(res, req):
        # we can pass whatever we want to context, query, headers or params, cookies etc
        context_value = req.preserve()

        # get all incoming data and parses as json
        body = await res.get_json()

        query = body["query"]
        variables = body.get("variables", None)
        root_value = body.get("root_value", None)
        operation_name = body.get("operation_name", None)

        data = await schema.execute(
            query,
            variables,
            context_value,
            root_value,
            operation_name,
        )

        res.cork_end(
            {
                "data": (data.data),
                **({"errors": data.errors} if data.errors else {}),
                **({"extensions": data.extensions} if data.extensions else {}),
            }
        )

    return post
    
```

In the socketify code path, get_json and req.preserve can be optimized (and we already have issues+tasks for it in progress), but outside it is only strawberry code that changes internally, I will need time to investigate the source code of strawberry.

**Comment by cirospaciari** [comment]
Maybe this is related:
https://github.com/strawberry-graphql/strawberry/issues/1886

**Comment by cirospaciari** [comment]
Timing only the scheme.execute part:

With and without async
![image](https://user-images.githubusercontent.com/6379399/221249333-6b9be9ee-5d86-4cf3-a7a7-78b8c216a0e4.png)

```python
start_time = time.monotonic()
data = await schema.execute(
            query,
            variables,
            context_value,
            root_value,
            operation_name,
)
end_time = time.monotonic()
print(timedelta(seconds=end_time - start_time))
        
```

**Comment by cirospaciari** [comment]
Maybe related:
https://github.com/cirospaciari/socketify.py/issues/102

**Comment by cirospaciari** [comment]
@wedobetter I will continue this next week, I have a lot of work to do today, but maybe my comments shine some lights here when under stress and after warmup PyPy gets faster than CPython.

**Comment by wedobetter** [comment]
> Maybe this is related:
> [strawberry-graphql/strawberry#1886](https://github.com/strawberry-graphql/strawberry/issues/1886)

I had never tried fastapi on PyPy and I have just tried PyPy + fastapi + strawberry, with the same code I am getting ~15ms responses

**Comment by dacevedo12** [comment]
Maybe related https://github.com/graphql-python/graphql-core/issues/190

**Comment by wedobetter** [comment]
@cirospaciari if I decide to go **sync**, does your server implementation act as a go webserver? i.e. does it handle each request in a system thread, i.e. concurrently or is it blocking on each request?

**Comment by wedobetter** [comment]
Right, thanks for your reply...
I know the threading deal with Python, I thought requests were handled by a multithreaded C written library, I have just realised I asked a silly question cause the main thread is Python anyway. 

As you said I need to experiment and see what works best, by the way I have dropped PyPy for now because I can't build GRPC libs with it, a old old annoying problem.

Thank you again!

**Comment by cirospaciari** [comment]
HPy project ia bringing compatibility with Cython and PyPy it may be solved by it self this year or next, I will not recommend PyPy for now if you depends on Cython libraries unless your benchmarks says that is worth.

Socketify + CPython are faster than japronto at this stage and will be even faster at the end of this year.

Hope that I can solve the issues you have with PyPy when I have some time.

**Comment by cirospaciari** [comment]
Some numbers:

Underpressure aka:
```bash
wrk --latency -d 5 -c 4096 --timeout 8 -t 8 http://localhost:8000 -s post.lua
```
post.lua:
```lua
wrk.method = "POST"
wrk.body = "{\"query\":\"query MyQuery {\\n  user {\\n    name\\n  }\\n}\",\"operationName\":\"MyQuery\"}"
wrk.headers["Content-Type"] = "application/json"
```
```python
from socketify import App
from strawberry.types import Info
from strawberry.utils.graphiql import get_graphiql_html

# this is the GQL helper as defined in the socketify docs
import strawberry
import strawberry.utils.graphiql

import time
from datetime import timedelta

@strawberry.type
class User:
    name: str


@strawberry.type
class Query:
    @strawberry.field
    async def user(self, info: Info) -> User:
        return User(name="Hello")





def run(app: App):
    schema = strawberry.Schema(Query)
    router = app.router()

    @router.get("/")
    def home(res, req): 
        res.end(get_graphiql_html())


    @router.post("/")
    async def post(res, req):
        # we can pass whatever we want to context, query, headers or params, cookies etc
        context_value = req.preserve()

        # get all incoming data and parses as json
        body = await res.get_json()
        
        query = body["query"]
        
        variables = body.get("variables", None)
        root_value = body.get("root_value", None)
        operation_name = body.get("operation_name", None)

        start_time = time.monotonic()

        data = await schema.execute(
            query,
            variables,
            context_value,
            root_value,
            operation_name,
        )
        end_time = time.monotonic()
        print(timedelta(seconds=end_time - start_time))

        res.cork_end(
            {
                "data": (data.data),
                **({"errors": data.errors} if data.errors else {}),
                **({"extensions": data.extensions} if data.extensions else {}),
            }
        )
```

Results:
```
0:00:00.053364
0:00:00.053202
0:00:00.052997
0:00:00.052786
0:00:00.052469
0:00:00.051713
0:00:00.051311
0:00:00.051040
0:00:00.050842
0:00:00.050672
0:00:00.050468
0:00:00.050253
0:00:00.050038
0:00:00.049820
0:00:00.049266
0:00:00.049026
0:00:00.048820
0:00:00.048654
0:00:00.048442
0:00:00.048273
0:00:00.048122
0:00:00.047974
0:00:00.047827
0:00:00.047505
0:00:00.047271
0:00:00.047092
0:00:00.046937
0:00:00.046789
0:00:00.046641
0:00:00.046495
0:00:00.046351
0:00:00.046136
0:00:00.045977
0:00:00.045660
0:00:00.045498
0:00:00.045343
0:00:00.045012
0:00:00.044752
0:00:00.044495
0:00:00.044233
0:00:00.043987
0:00:00.043718
0:00:00.043223
0:00:00.043045
0:00:00.042884
0:00:00.042730
0:00:00.042576
0:00:00.042426
0:00:00.042277
0:00:00.042128
0:00:00.041979
0:00:00.041604
0:00:00.041417
0:00:00.041252
0:00:00.041096
0:00:00.040912
0:00:00.040749
0:00:00.040599
0:00:00.040450
0:00:00.040302
0:00:00.040011
0:00:00.039838
0:00:00.039647
0:00:00.039504
0:00:00.039356
0:00:00.039208
0:00:00.039059
0:00:00.038913
0:00:00.038769
0:00:00.038623
0:00:00.038314
0:00:00.038153
0:00:00.037998
0:00:00.037848
0:00:00.037698
0:00:00.037551
0:00:00.037406
0:00:00.037262
0:00:00.037793
0:00:00.037475
0:00:00.037311
0:00:00.037157
0:00:00.037010
0:00:00.036864
0:00:00.036680
0:00:00.036519
0:00:00.036374
0:00:00.036230
0:00:00.035902
0:00:00.035733
0:00:00.035576
0:00:00.035424
0:00:00.036180
0:00:00.035951
0:00:00.035792
0:00:00.035641
0:00:00.035496
0:00:00.035203
0:00:00.035032
0:00:00.034872
0:00:00.034720
0:00:00.034569
```

**Comment by cirospaciari** [comment]
With no pressure same code:
Results:
```bash
0:00:01.558609
0:00:01.405271
0:00:01.529131
0:00:01.549445
0:00:01.733283
0:00:00.119836
0:00:01.210686
0:00:01.441472
0:00:01.571545
```

**Comment by cirospaciari** [comment]
Traced down to:
https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/schema/execute.py#L128-L142

with is:
```python
from graphql import execute as original_execute
```

This await call that is taking too long in case is `graphql.execute` result that is handing too much for some reason, i will investigate further on `graphql` package.

**Comment by cirospaciari** [comment]
After a quick look, when using futures (aka get_data/get_json etc) graphql is impacted, when not using it graphql is not affected, this is a really odd behavior, using futures or asyncio.Queue gives the same result.

The new helper avoids using get_data/get_json and is 3x faster when not under pressure, only when not under pressure can we feel the latency, this might be something on socketify loop.py, and https://github.com/cirospaciari/socketify.py/issues/102 can be related or not. Further investigations are needed, i will take some time this weekend to look more at it.

New Helper:
https://github.com/cirospaciari/socketify.py/blob/main/examples/helpers/graphiql.py

**Comment by cirospaciari** [comment]
The second Hypothesis was the right answer.
I will change run_once to run_nowait and this will be fixed. I need time to do tests and release a new version so @wedobetter I will commit to main the fix and at the end of the day or tomorrow morning I will publish the new version.

The new helper will have a little less overhead, but in practice will not be that much difference.
