### ISSUE TITLE
[WSGI] Memory leak (only Windows)

### ISSUE THREAD

**Issue by remittor** [cirospaciari/socketify.py#113]
**Describe the bug**
Memory leak on `"Hello World!"` infinite test.

**To Reproduce**
Run any `"Hello World!"` test on localhost.

**Screenshots**
![image](https://user-images.githubusercontent.com/9350115/224946301-f4498d5d-d43f-4de7-b70b-435bb978ed9c.png)

**Desktop:**
 - OS: Windows 7 64-bit
 - Python: 3.8.10 64-bit
 - Version: master branch (2022-03-14)

**Comment by cirospaciari** [comment]
Thanks for reporting I will take a look!

**Comment by cirospaciari** [comment]
Checklist to me:
- [ ] Check if it occurs on Windows 10 (Python 3.8, 3.9, 3.10, and 3.11)
- [ ] Check if it occurs on Windows 11 (Python 3.8, 3.9, 3.10, and 3.11)
- [ ] Check if is socketify or uWS leaking

**Comment by cirospaciari** [comment]
Closed as duplicated https://github.com/cirospaciari/socketify.py/issues/115
