### ISSUE TITLE
Segfault on high-load HTTP pipelining test

### ISSUE THREAD

**Issue by remittor** [cirospaciari/socketify.py#114]
**Describe the bug**
Segfault 

**To Reproduce**
Server: simple `"Hello World!"` test.
Client: `python3 pl_test.py`
File `pl_test.py`: https://gist.github.com/remittor/f2c89f50ff259e6e704fe246ee6c3dd5

Server output:
```
> python3 si_test.py -g si -v 8
2023-03-14 09:30:26,851 [DEBUG] Using selector: EpollSelector
Listening on port http://localhost:5000 now

Segmentation fault
```
Client output:
```
Run test 2 ...
totalsent = 13654894, totalrecv = 266240
LastResp: b'/1.1 200 OK\r\nContent-Type: text/plain\r\nDate: Tue, 14 Mar 2023 10:22:26 GMT\r\nServer: uWebSockets_20\r\nTransfer-Encoding: chunked\r\n\r\nc\r\nhello world!\r\n0\r\n\r\nHTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nDate: Tue, 14 Mar 2023 10:22:26 GMT\r\nServer: uWebSockets_20\r\n'
Traceback (most recent call last):
  File "/home/user/wsgi/pl_test.py", line 69, in <module>
    rc = sock.send(payload_huge[totalsent:])
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Desktop (please complete the following information):**
 - OS: Debian 11 64-bit (and Windows 7)
 - Python: 3.9
 - Version: master branch

**Comment by cirospaciari** [comment]
Thanks for reporting I will take a look!

**Comment by cirospaciari** [comment]
Seems to be a bug with chunked encoding I will publish an 0.0.19 soon with uWS updates https://github.com/uNetworking/uWebSockets/commit/8410f7ee6b5ac6acc9fd28c2abdcd728648c18de
