### ISSUE TITLE
Add relax strategy to relieve CPU usage

### ISSUE THREAD

**Issue by cirospaciari** [cirospaciari/socketify.py#118]
Today loop.py just keeps calling run_nowait to be able to run the python event loop in the same thread.

Adding an relax strategy or another integration is crucial before v1.0.0

**Comment by remittor** [comment]
I solved the same problem in this way:
https://github.com/remittor-pr/fastwsgi/commit/fa7adb31dbcef926426879abf596bd71afa47fec

**Comment by cirospaciari** [comment]
> I solved the same problem in this way: [remittor-pr/fastwsgi@fa7adb3](https://github.com/remittor-pr/fastwsgi/commit/fa7adb31dbcef926426879abf596bd71afa47fec)

Thanks, I will take a look this weekend, I already have some versions using a check, prepare, and idle handle for libuv too on the works.

**Comment by EnricoBeltramo** [comment]
Will those fixes will be applied soon? I too am having some CPU usage issues. Thank you

**Comment by cirospaciari** [comment]
Will be closed this weekend sorry about that

**Comment by cirospaciari** [comment]
> Will those fixes will be applied soon? I too am having some CPU usage issues. Thank you

This will solve it https://github.com/cirospaciari/socketify.py/commit/a63b75e30a99cd82134642e6a82f6f4c48361dc3 just need to test more before releasing this one
