### ISSUE TITLE
socketify 0.0.20 High CPU usage

### ISSUE THREAD

**Issue by masksshow** [cirospaciari/socketify.py#119]
Hello!
Great project. Respect!

problem: 100% cpu.
https://github.com/cirospaciari/socketify.py/issues/112

You fixed this problem in version 0.0.19
But in version 0.0.20  the problem is again.
I used docker for this. and checked your versions.

**Comment by cirospaciari** [comment]
closed in favor of https://github.com/cirospaciari/socketify.py/issues/118
