### ISSUE TITLE
UUID websocket handler

### ISSUE THREAD

**Issue by EnricoBeltramo** [cirospaciari/socketify.py#124]
**Is your feature request related to a problem? Please describe.**
Is it possible to have an UUID from websocket handle in order to discriminate in unique way the source of messages / websocket connected / disconnected?

**Describe the solution you'd like**
i.e. when a message coming, a parameter like an id in ws parameter to get the source of message
def ws_message(ws, message, opcode)
    id = ws.id

**Describe alternatives you've considered**
-

**Additional context**
In websocket library, when I have a websocket handler it is associated an uuid, I would to have similar feature here too

**Comment by cirospaciari** [comment]
You can have any data you wanna if you upgrade with it like in the chat example: https://github.com/cirospaciari/socketify.py/blob/main/examples/chat/index.py
If you have any user_data when upgrading socketify generates an uuid for you and you can use `ws.get_user_data_uuid()` and you can retrieve the data using `ws.get_user_data()`

**Comment by EnricoBeltramo** [comment]
Thank you, I tried get_user_data() but it return always None. So, if I understood well, I have to call upgrade and set some user data in order to have valid value in ws.get_user_data()

**Comment by cirospaciari** [comment]
> Thank you, I tried get_user_data() but it return always None. So, if I understood well, I have to call upgrade and set some user data in order to have valid value in ws.get_user_data()

Yes you need to upgrade with some data that can be anything you wanna.
