### ISSUE TITLE
Running a Django WSGI Application

### ISSUE THREAD

**Issue by mthbrown** [cirospaciari/socketify.py#125]
I'm trying to use socketify to run a Django WSGI application. However, it fails on any request:

```
$ python3 -m socketify django_project.wsgi:application
Listening on http://127.0.0.1:8000 now

Exception ignored from cffi callback <function wsgi at 0x7f9bbf496a20>:
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/pages/lib64/python3.11/site-packages/socketify/wsgi.py", line 458, in wsgi
    app_iter = app.wsgi(environ, start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/pages/lib64/python3.11/site-packages/django/core/handlers/wsgi.py", line 123, in __call__
    request = self.request_class(environ)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/pages/lib64/python3.11/site-packages/django/core/handlers/wsgi.py", line 78, in __init__
    self._stream = LimitedStream(self.environ["wsgi.input"], content_length)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/pages/lib64/python3.11/site-packages/django/core/handlers/wsgi.py", line 24, in __init__
    self._read = stream.read
                 ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'read'
Error: Returning from a request handler without responding or attaching an abort handler is forbidden!
terminate called without an active exception
Aborted (core dumped)
```

This is just a standard Hello World application. Any ideas? Thanks

**Comment by cirospaciari** [comment]
Hey, thanks for reporting, can you tell me the python version you are using, Operational System and packages versions? I wanna to reproduce this here to fix it

**Comment by mthbrown** [comment]
Here is how you can recreate it (Python 3.11.3):

```
git clone https://github.com/wsvincent/djangoforbeginners
cd djangoforbeginners/
cd ch3-pages/
pyenv virtualenv system myproject
echo "myproject" > .python-version
pip install -r requirements.txt
pip install socketify
```

If you then run:

```
python manage.py runserver 8001
```

and open your browser, you get back the page as expected

If you then stop it and run this instead:

```
python3 -m socketify django_project.wsgi:application -p 8001
```

you get the error I mentioned

**Comment by cirospaciari** [comment]
Django is missing checks but we are in the spec:

"Currently environ['wsgi.input'] points to a stream that represents the body of the HTTP request. Once this stream has been read, it cannot necessarily be read again. It may not have a seek method (none is required by the WSGI specification, and frequently none is provided by WSGI servers)."

https://wsgi.readthedocs.io/en/latest/specifications/handling_post_forms.html
I will add a empty body and also set the CONTENT_LENGTH to zero just in case.

**Comment by cirospaciari** [comment]
Added in this commit https://github.com/cirospaciari/socketify.py/commit/99e716e65711ffb73e0ba6a3fe172d5e61b6dba3
I will test it and add more fixes on this patch, and will publish the release until end of tomoroow

**Comment by mthbrown** [comment]
@cirospaciari Thanks. Gave it a quick test run and so far so good. I'm still going through some Django examples (still learning Django actually) so if you want, you can either keep the issue open while I do more testing or close it and I'll create a new issue if I run into anything.

**Comment by cirospaciari** [comment]
Thanks @mthbrown i will keep it open, if you find anything just ping me please

**Comment by mthbrown** [comment]
@cirospaciari One thing I noticed is that even when running even with no incoming requests, it takes up basically 100% CPU of the number of workers I configure it to use

**Comment by cirospaciari** [comment]
Yeah I added a CPU relax strategy on my last commit so now should be fine, probably tomorrow I will add more fixes and release a new version

**Comment by cirospaciari** [comment]
new release is out so I will close this Issue, if you find anything else, please feel free to open a new one
