### ISSUE TITLE
Asynchronous WebSocket close handler function do not work

### ISSUE THREAD

**Issue by andrew127** [cirospaciari/socketify.py#127]
**Describe the bug**
Asynchronous version of WebSocket close handler function fails

**To Reproduce**
1. Run the following code:
```python
from socketify import App, AppListenOptions


async def ws_open(ws):
    print("A WebSocket got connected!")

async def ws_message(ws, message, opcode):
    print('got message')

async def ws_close(ws, code, message):
    print('Closing', code)


app = App()
app.ws('/*', {
    'open': ws_open,
    'message': ws_message,
    'close': ws_close
})
app.listen(AppListenOptions(port=8765, host="0.0.0.0"), lambda config: print('Listening on port %d' % config.port))
app.run()
```
2. Connect to the server with WebSocket client
3. Send any message from client over the WebSocket connection
4. See the "got message" in console - indication that async message handler works fine
5. On the client side, close WebSocket connection
6.  Server will output the  following error into the console:
```
ERROR:root:Uncaught Exception: uws_websocket_close_handler.<locals>.wrapper() missing 1 required positional argument: 'dispose'
```

**Expected behavior**
It is expected asynchronous call to close handler will work without error. When non async close handler used, it outputs correct closing message on above test scenario:
```
Closing 1000
```

**Server info**
 - OS: Ubuntu 22.04.2 LTS x64
 - Version 0.0.22

**Additional context**
Non asynchronous  version of close event handler works fine

**Comment by cirospaciari** [comment]
Thanks for reporting it! I will fix it soon and do a new fix release thanks!
