### ISSUE TITLE
Process still cannot be terminated by CTRL+C

### ISSUE THREAD

**Issue by amchii** [cirospaciari/socketify.py#131]
**Describe the bug**
Similar to this issue https://github.com/cirospaciari/socketify.py/issues/103, processes cannot be terminated by Ctrl+C.

**To Reproduce**
A simple fastapi app:
```python
from fastapi import FastAPI
from fastapi.responses import JSONResponse

app = FastAPI()


@app.get("/")
async def index():
    return JSONResponse({"hello": "world"})

```
run `python -m socketify app:app --workers 8 --disable-listen-log`,
then use `CTRL+C` to terminate it

**Screenshots**
![image](https://github.com/cirospaciari/socketify.py/assets/26922464/1a8b5fed-da67-4d24-9503-e32a96bd9839)
Double `CTRL+C` will exit this, but run `ps -ef | grep socketify` indicates that the process has not been terminated.
![image](https://github.com/cirospaciari/socketify.py/assets/26922464/69f929c6-bb78-479f-af8e-617154dac219)

**Additional context**
Ubuntu 20.04, zsh
Python3.11.4
socketify version: 0.0.24

**Comment by cirospaciari** [comment]
Thanks for reporting, I publish the version `v0.0.25` right now, this should work fine now.
