### ISSUE TITLE
Running background coroutine 

### ISSUE THREAD

**Issue by GoEdgar** [cirospaciari/socketify.py#137]
Tried to create background task like "broadcaster for active connections" within FastAPI's startup lifespan and got "no running event loop". Some research show me that FastAPI's coroutine is being started outside loop via "custom futures", which is manually "scrolling" by socketify. Since I didn't find anything about architecture and lifetime cycle of socketify, I can't answer myself. Is it able to solve my problem? For performance reasons, it would be nice to perform python code as less as possible, so should I plan broadcasting by another way like "python-coro-callback-from-uvloop-after-some-time" or something similar?

``` python
@asynccontextmanager
async def lifespan(app: FastAPI):
    task = asyncio.create_task(broadcaster.start_broadcast())
    yield
    task.cancel()
```

**Comment by bitnom** [comment]
I have just run into this as well. Please let me know what (If anything) you come to do about it ahead of any related PR.
