### ISSUE TITLE
Deployment with 1 worker always consumes 0.1 cpu

### ISSUE THREAD

**Issue by SnoozeFreddo** [cirospaciari/socketify.py#152]
A basic deployment on AWS shows that socketify consumes 0.11-0.12 cpus while idle. The same applies locally while other applications almost don't consume any cpu at all.

**Comment by goteguru** [comment]
Confirmed. Exact figures depends on the hardware of course. On my case (oracle cloud / AMD EPYC) single process eats as high as ~4-8% while idle! In comparison same code with FastAPI/uvicorn consumes about 0.1-0.2% (while idle).

That's pretty high... (doesn't seem to be scalable).

**Comment by leunga1000** [comment]
I see this too, about .1 cpus consistently

**Comment by goteguru** [comment]
> I see this too, about .1 cpus consistently
Author is aware of the problem, it might be a good idea to add some kind of config option.
For now, you can modify the source to reduce the idle load  (in expense of reactivity after sleeping).

Look for Loop._keep_alive() here and increase the relaxed state callback time from 0.001 to something sensible according to you use-case: 
https://github.com/cirospaciari/socketify.py/blob/main/src/socketify/loop.py

**Comment by leunga1000** [comment]
Thanks for this, really helps! I have patched the method locally to reduce the cpu usage and will see how it affects functionality and performance.

**Comment by cirospaciari** [comment]
In the future this will be a configuration but for now if we are idle we wait for 1ms and if we are idle for 5s we wait for 10ms (little less agressive) you can set the time using:

```python
from socketify import App
import asyncio 
# idle_relaxation_time is in seconds and defaults to 0.01, this is set after 5s of idle time
app = App(idle_relaxation_time=0.1)

router = app.router()

@router.get("/")
def home(res, req, data=None):
    res.send({"Hello": "World!"})


app.listen(
    3000,
    lambda config: print("Listening on port http://localhost:%d now\n" % config.port),
)
app.run()
```
be aware that is a temporary solution until we get a proper asyncio integration, and this will make a request takes longer if the application is idle
