### ISSUE TITLE
Create a background task in event loop

### ISSUE THREAD

**Issue by EnricoBeltramo** [cirospaciari/socketify.py#154]
**Is your feature request related to a problem? Please describe.**
I would create a background task to do some timerized operation i.e. periodical send some data update to all clients connected

**Describe the solution you'd like**
something like app.create_background_task(callback)

**Comment by cirospaciari** [comment]
I will take this in consideration so in the native extension version we can have this feature added

**Comment by cirospaciari** [comment]
> +1, is there any workaround to get a periodic task to fire?

You can register it in the default loop in asyncio using pure python for now

**Comment by chask-stealth-mode** [comment]
Not sure if this is wha

> I tried a few ways to get it to register, but I keep getting errors and I think I'm not handling the registration properly. I keep seeing errors like "Cannot run the event loop while another loop is running." Could you maybe help me with a simple example? How could I add the bg_task to the loop below? Thanks - a bit new to asyncio loops and want to make sure to get this right without degrading the performance of socketify (which is incredible btw)
> 
> ```
> from socketify import App,
> app = App()
> 
> async def bg_task():
>     while True:
>         await asyncio.sleep(60)
>         logger.info("Running task")
> 
> 
> def start():
>     app.listen(PORT, HOST)
>     logger.info(f"Listening on http://{HOST}:{PORT}")
>     # how do i add the the thread 
>     app.run()
> 
> 
> if __name__ == '__main__':
>     start()
> ```

Not sure if this is what you wanted to achieve. If it helps, I have this socketify GPT that helps me a lot! https://chat.openai.com/g/g-ZSUkRkncp-socketify-doc-assistant

import asyncio
import threading
from socketify import App
import logging

logger = logging.getLogger(__name__)
app = App()

async def bg_task():
    while True:
        print("Background task is running...")
        await asyncio.sleep(2)
        logger.info("Background task running")

def run_socketify_app():
    app.listen(3050, 'localhost')
    print("Socketify app is running...")
    logger.info("Listening on http://localhost:3050")
    app.run()

def run_bg_task():
    asyncio.run(bg_task())

def start():
    # Run background task in a separate thread
    thread = threading.Thread(target=run_bg_task)
    thread.start()

    # Run Socketify app in the main thread
    run_socketify_app()

if __name__ == '__main__':
    start()

**Comment by cirospaciari** [comment]
for now you can do like:
```python
from socketify import App, AppOptions
import asyncio
app = App()

def home(res, req):
    res.end("Hello World socketify from Python!")
app.get("/", home)
app.listen(3000, lambda config: print("Listening on port http://localhost:%d now\n" % config.port))


async def bg_task():
    while True:
        print("Background Task")
        await asyncio.sleep(1)

def on_start():
    app.loop.ensure_future(bg_task())

app.loop.loop.call_soon(on_start)  
# app will run on the default loop
app.run()
```

This will change this year to a easier way
