### ISSUE TITLE
App can't be hit with http call when executed via CLI

### ISSUE THREAD

**Issue by danjoyboy** [cirospaciari/socketify.py#167]
Hi @cirospaciari I was unable to run socketify with CLI

I was using the exact same command as mentioned in the docs (by defining run function that retrieve app as arg)

the app shown its running but when I hit using curl/postman the request is hanging

any resolution for this?

thanks in advance!

**Comment by cirospaciari** [comment]
Can you show me a minimal reproduction? The command line and the app.py?

**Comment by danjoyboy** [comment]
main.py
```
from socketify import App

app = App()

def run(app: App):
    app.get("/", lambda res, req: res.end("Hello worldddddd!!!"))
```

cmd
```
python -m socketify main:run
```

**Comment by danjoyboy** [comment]
anyway nvm, I could hit the app by removing this line
```
app = App()
```

into this
```
from socketify import App

def run(app: App):
    app.get("/", lambda res, req: res.end("Hello worldddddd!!!"))
```

and now its working.. thanks! for the response!
