### ISSUE TITLE
flask request.args contains the (?arg) with socketify wsgi

### ISSUE THREAD

**Issue by altunyurt** [cirospaciari/socketify.py#170]
**Describe the bug**
I've tried flask with many other wsgi servers without any problems, but running the same application with socketify as follows, causes the app to receive query string arguments as (?arg, val) instead of (arg, val)

**To Reproduce**

Run a flask application containing an endpoint defined as follows 

```py
from flask import request
...
@app.route("/", methods=["GET"])
def index():
    print(request.args)
    return ""
```

Run the application with socketify
```
python -m socketify app:app -w 1 -p 9000 --interface wsgi
```
Request a url on the app, say: http://localhost:9000/?page=1
It will print out  ```ImmutableMultiDict([('?page', '1')])```

**Expected behavior**
It should print out ```ImmutableMultiDict([('page', '1')])```
which is the correct print out when the same app is run with flask dev server or any other wsgi server. 

Versions 
socketify 0.0.27
flask 3.0.3
python 3.9.7

**Comment by cirospaciari** [comment]
fixed by https://github.com/cirospaciari/socketify.py/commit/30cec004e0d7f94c1cd9384917746eae345c81a2
will be release in v0.0.29
