### ISSUE TITLE
Get request body 

### ISSUE THREAD

**Issue by mardon86** [cirospaciari/socketify.py#179]
One of example code from https://docs.socketify.dev/routes.html:
```
async def home(res, req):
    body = await res.get_json()     #<------
    user = await get_user(body)
    res.cork_end(f"Hello World! {user.name}")

app.post("/", home)
```

What's the meaning of 'res' and 'req', is it response and request ?
why do we get request body content from 'res' not from 'req' ?
thx

**Comment by cirospaciari** [comment]
Is response and request the API reflects the uWS API with I also don't agree with, this will be change with the next API
