### ISSUE TITLE
Regression in v0.0.28: high CPU consumption in idle mode

### ISSUE THREAD

**Issue by Aksem** [cirospaciari/socketify.py#194]
Running server eats the whole CPU core without a reason(=consumes 12.5% of CPU in 8 Core system). 

**To Reproduce**
1. Use socketify v0.0.28.
2. Start the simple server from official example:
```
from socketify import App

app = App()
app.get("/", lambda res, req: res.end("Hello World socketify from Python!"))
app.listen(3000, lambda config: print("Listening on port http://localhost:%d now\n" % config.port))
app.run()
```
3. Check CPU consumption of the process.

**Expected behavior**
CPU consumption should be low.

**Screenshots**
-

**Desktop:**
 - OS: Linux (openSUSE Tumbleweed)
 - Browser: -
 - Version: -

**Additional context**
v0.0.27 works as expected

**Comment by cirospaciari** [comment]
After 5s the CPU consumption was still high?

**Comment by Aksem** [comment]
Yes, it stays high as long as the process runs(tried to keep for 5 minutes in the last test of minimal example).

**Comment by cirospaciari** [comment]
Ok will revert the last change on this thing before publishing the new version Thanks for the feedback

**Comment by ArthoPacini** [comment]
Can confirm, it goes brrrrr on 0.0.28, needed to downgrade to 0.0.27.

Any preview for release? BOM TRABALHO DOUTOR!

**Comment by cirospaciari** [comment]
Sorry the delay, I just move to San Francisco CA but will release this week! sorry about that!

VLW MANO bora fazer isso ficar melhor hahah vou me dedicar mais \o
