### ISSUE TITLE
Fix MacOS M1 and M2 builds, Maybe link zlib and libuv statically in macOS 

### ISSUE THREAD

**Issue by cirospaciari** [cirospaciari/socketify.py#34]
Add zlib and libuv statically instead of dynamically linked, this will avoid problems with people that don't run.

``` 
brew install libuv
brew install zlib
```
or 
```
apt install libuv1 zlib1g
```

Discussion: https://github.com/cirospaciari/socketify.py/discussions/10#discussioncomment-4129980

(Should fix arm m2)

**Comment by cirospaciari** [comment]
@seanr3 I'm trying to fix the build for Apple Silicon, today i will fix that, sorry for the delay, but now is the priority.

**Comment by cirospaciari** [comment]
Still not solved
![image](https://user-images.githubusercontent.com/6379399/203642111-d82329c7-e145-46bd-ad3d-bc9d2dbc7c02.png)

```_uv_async_init``` error on is libuv not being detected or properly linked

**Comment by seanr3** [comment]
Yup same here.

**Comment by cirospaciari** [comment]
Still trying to figure it out an pre-build for Apple Silicon, but for now the only way is building from source, github has a roadmap to include M1 powered runners and an paid version is available from CirrusLabs but is just too expensive for this project at this stage (without more funding or customers), I'm also checking the possibility of using macOS M1 from AWS to build this, and checking an way to statically link cross compiled libuv and zlib for M1

Manual build:

```bash
brew install libuv
brew install zlib
brew install libuv --HEAD
brew install zlib --HEAD

#clone and update submodules
git clone https://github.com/cirospaciari/socketify.py.git
cd ./socketify.py
git submodule update --init --recursive --remote
cd ./src/socketify/native/ && make macos-arm64 && cd ../../../
#install local pip
python3 -m pip install .
```

**Comment by cirospaciari** [comment]
@seanr3 Good news, i created an new process to cross-compile libuv statically using cmake and things worked here!
![image](https://user-images.githubusercontent.com/6379399/203813364-c2d14199-db78-40da-a4e5-c25d1780c2ec.png)

No need to build manually anymore.

```bash
```

**Comment by seanr3** [comment]
Works! Thank you.
