### ISSUE TITLE
HTTPS not working: RuntimeError: Failed to create connection

### ISSUE THREAD

**Issue by bob-rove** [cirospaciari/socketify.py#85]
**Describe the bug**

Unable to run `examples/https.py` neither with  certificate bundled with `socketify` nor with created by `openssl` command supplied within `https.py`.

**To Reproduce**

Setup env with `docker run --rm -it python:3.9.13-slim-bullseye bash -l` :

```bash
apt-get update
apt install libuv1 zlib1g
pip install socketify
```

add `https.py` script:
```bash
cat <<-EOF> https.py
from socketify import App, AppOptions

app = App(
    AppOptions(
        key_file_name="/usr/local/lib/python3.9/site-packages/socketify/uWebSockets/misc/key.pem",
        cert_file_name="/usr/local/lib/python3.9/site-packages/socketify/uWebSockets/misc/cert.pem",
        passphrase="1234",
        dh_params_file_name=None,
        ca_file_name=None,
        ssl_ciphers=None,
    )
)
app.get("/", lambda res, req: res.end("Hello World socketify from Python!"))
app.listen(
    3000,
    lambda config: print("Listening on port https://localhost:%d now\n" % config.port),
)
app.run()
EOF
```
run `python ./https.py`
```
Traceback (most recent call last):
  File "//./https.py", line 3, in <module>
    app = App(
  File "/usr/local/lib/python3.9/site-packages/socketify/socketify.py", line 2539, in __init__
    raise RuntimeError("Failed to create connection")
RuntimeError: Failed to create connection
```

**Expected behavior**

`examples/https.py` should work.

**Extra context**

```bash
# uname -a
Linux 875b757ff0e5 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 x86_64 GNU/Linux
```

Reproducible with `venv` and without.

**Comment by cirospaciari** [comment]
@bob-rove Thanks for reporting it! I will take a look at it soon.

**Comment by bob-rove** [comment]
@cirospaciari I've found that installing `clang` package with dependencies is fixing the problem with bundled certificate.

But there is still the same issue if I use my own certificate, generated with this command supplied in `examples/https.py`:
```
openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -passout pass:1234 -keyout ./misc/key.pem -out ./misc/cert.pem
```

**Comment by cirospaciari** [comment]
socketify itself does not depend on clang after being compiled, I did not test yet but the command in https.py must be wrong, the bundled certificated is not supposed to be used (I may remove it), but should work if not expired.

I have a lot of work to do today, so I may check this only tomorrow.
Thanks for testing.

Is probably only a matter of using a proper certificate.

**Comment by bob-rove** [comment]
By reducing `clang` dependencies I discovered that only `media-types` package was missing.
Yet, running `apt install -y libuv1 zlib1g media-types` on top of raw `python:3.9.16-slim-bullseye` image is not enough to start server in TLS mode. I had to `import asyncio` as 1st line of code in `https.py` to make it finally working with bundled certificates.

The problem with newly generated certificates seems to be related to something else (in `socketify` ?).
I tried saving certificate in different places on the filesystem and I was able to start server in TLS mode when certificate was placed in exactly the same folder with bundled one: `/usr/local/lib/python3.9/site-packages/socketify/uWebSockets/misc/`. Using any other path (overlay `/`, `/tmp` and even mounted `/app`) didn't work for me.

**Comment by bob-rove** [comment]
I also tried using `dh_params_file_name` option with a certificate I intend to use (all works with Nginx), but getting the same error:
```
  File "/opt/venv/lib/python3.9/site-packages/socketify/socketify.py", line 2539, in __init__
    raise RuntimeError("Failed to create connection")
```
If I use key and cert with `dh_params_file_name=None` server starts and replying fine.

Should I create another issue to fix `dh_params_file_name` option?

**Comment by cirospaciari** [comment]
🧐 I think we can keep this issue o will investigate this dependencies on media-type and also the dh_params_file_name, maybe is some compiler option or issue in uWebSockets/uSockets, I will change the title to investigate the behavior and check All options, o also need to add unit tests for all this cases

**Comment by cirospaciari** [comment]
> By reducing `clang` dependencies I discovered that only `media-types` package was missing. Yet, running `apt install -y libuv1 zlib1g media-types` on top of raw `python:3.9.16-slim-bullseye` image is not enough to start server in TLS mode. I had to `import asyncio` as 1st line of code in `https.py` to make it finally working with bundled certificates. NB: `import asyncio` wasn't required in case of plain HTTP.
> 
> The problem with newly generated certificates seems to be related to something else (in `socketify` ?). I tried saving certificate in different places on the filesystem and I was able to start server in TLS mode when certificate was placed (under any filename) in exactly the same folder with bundled one: `/usr/local/lib/python3.9/site-packages/socketify/uWebSockets/misc/`. Using any other path (overlay `/`, `/tmp` and even mounted `/app`) didn't work for me.

Is really weird that you need to add media-types and also import asyncio, I can't imagine why, socketify it self already import Loop that uses asyncio

**Comment by bob-rove** [comment]
> Is really weird that you need to add media-types and also import asyncio, I can't imagine why, socketify it self already import Loop that uses asyncio

I've noticed, but have no clue what might be causing this. The issue is consistently reproducible.
Just for completeness I've added the value `uname -a` in container I use for these tests.

**Comment by cirospaciari** [comment]
media-types maybe because I used mimetypes.init() in helpers? I will investigate it tomorrow for sure

**Comment by cirospaciari** [comment]
I will need some time or help to investigate this because I basically working 12h to 16h per day, but its my priority for sure!

**Comment by cirospaciari** [comment]
Actual i discover the issue, at some point CFFI stop sending the data and premature clean SSL options (some times worked some times not)
Please update to v0.0.10

**Comment by bob-rove** [comment]
Thanks a mil @cirospaciari ! 🙇 
I confirm - the issue with `AppOptions` defaults, ability to omit them and to specify certs outside of the `socketify` package path is fixed according to my quick tests. 🚀 

> I will need some time or help to investigate this because I basically working 12h to 16h per day, but its my priority for sure!
No worries at all - I believe this is a great and well-anticipated project that solves one problem well and across a lot of platforms with help of well designed low-level library `us/uws`. More people will come with help as time goes, especially given the traction your work found in `bun` framework. Very well done Ciro!
And even though I can't be useful on a lower level, I'll do my best to report and test any of mine findings.

**Comment by cirospaciari** [comment]
> Thanks a mil @cirospaciari ! bow I confirm - the issue with `AppOptions` defaults, ability to omit them and to specify certs outside of the `socketify` package path is fixed according to my quick tests. rocket
> 
> > I will need some time or help to investigate this because I basically working 12h to 16h per day, but its my priority for sure!
> 
> No worries at all - I believe this is a great and well-anticipated project that solves one problem well and across a lot of platforms with help of well designed low-level library `us/uws`. More people will come with help as time goes, especially given the traction your work found in `bun` framework. Very well done Ciro! And even though I can't be useful on a lower level, I'll do my best to report and test any of mine findings.

Thanks :heart: I will do my best always, comment like this give me more motivation to do even better :heart:

**Comment by bob-rove** [comment]
Always welcome! I can imagine how such a great project can be excited and with more popularity many more issues will be reported. In the meantime - don't forget to have enough rest! 😅
